export { default as Home } from './home/Home';
export { default as About } from './about/About';
export { default as Services } from './services/Services';
export { default as Projects } from './projects/Projects';
export { default as Contact } from './contact/Contact';
export { default as Quotation } from './quotation/Quotation';
export { default as PageNotFound } from './PageNotFound/PageNotFound';
export { default as QuoteSubmitted } from './QuoteSubmitted/QuoteSubmitted';
export { default as ContactSubmitted } from './ContactSubmitted/ContactSubmitted';